[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"
  # Supabase Configuration - CRITICAL FOR BUILD
  NEXT_PUBLIC_SUPABASE_URL = "https://hpkxmotzidywoilooqpx.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwa3htb3R6aWR5d29pbG9vcXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODg2MzcsImV4cCI6MjA2OTg2NDYzN30.KbbrGQPzXcO3SBRvXk2ySdCzprNiUXCnQZdiQRgCuNc"

# Fix Clerk authentication routing
[[redirects]]
  from = "/sign-in/*"
  to = "/sign-in"
  status = 200

[[redirects]]
  from = "/sign-up/*"
  to = "/sign-up"
  status = 200

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Force dynamic rendering
[functions]
  directory = ".next/server"

# Ensure all dependencies are installed
[build.processing]
  skip_processing = false
